### PR TITLE
Add checksum to release notes

### PR DESCRIPTION
**Pull request by kfox1111**
SPIRE needs a checksum specified in order to load the plugins. This change adds the checksums of released plugins to the release notes in github so users don't have to try and calculate them after download.

### CODE REVIEW

**Comment by matthewdevenny** [comment]
Thanks... I think it might be better to add them as release text file artifacts though - which is something I thought about adding and then got distracted.

**Comment by kfox1111** [comment]
That would work too. Just looking for an easy place to find them for the containers, so you don't have to extract the file from the containers which can be a bit tricky.

**Comment by matthewdevenny** [comment]
Something like this...
https://github.com/boxboat/spire-tpm-plugin/releases/tag/v1.8.7-rc1

**Comment by kfox1111** [comment]
Yeah, that looks perfect. We can close this in favor of that if you'd like.

Thanks! :)

**Comment by matthewdevenny** [comment]
Release checksum text files added to 1.8+

**Pull request closed without merging**
